server:
  port: 2000
  max-http-header-size: 3000
  undertow:
    threads:
      io: 32
    direct-buffers: true

spring:
  application:
    name: consumer
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# Dubbo Config properties
dubbo:
  application:
    metadata-type: local
    id: ${spring.application.name}
    name: ${spring.application.name}
    version: 1.0.0
  provider:
    timeout: 100000
  consumer:
    timeout: 100000

  registry:
    id: none
    # 不使用注册中心
    address: N/A

